/* Sanātana Vṛkṣa — content data. */
export const SVData = {
  nav: ["Home","About","Services","Classes","Grow","Vṛkṣa Vāṇī","Membership","Our Offerings","Donate","Contact"],

  categories: [
    { id:"homas", glyph:"अ", title:"Homas", desc:"Sacred fire rituals for health, prosperity, protection, peace, and spiritual upliftment.", target:"homas" },
    { id:"poojas", glyph:"ॐ", title:"Poojas", desc:"Traditional deity worship performed with devotion, mantras, offerings, and proper procedure.", target:"poojas" },
    { id:"samskaras", glyph:"ૐ", title:"Samskaras", desc:"Life-milestone ceremonies from birth to marriage and beyond, rooted in Vedic tradition.", target:"samskaras" },
    { id:"special", glyph:"श्री", title:"Specialized Poojas", desc:"Personalized spiritual services for specific needs, family occasions, guidance, and blessings.", target:"specialized" },
  ],

  homas: [
    { name:"Dhanvantari Homa", dev:"धन्वन्तरि होम", glyph:"धं", img:"/assets/homas/h2.jpg", desc:"Invoked for health, healing, and recovery from illness.", price:"from $251" },
    { name:"Durgā Homa", dev:"दुर्गा होम", glyph:"दुं", img:"/assets/homas/h3.jpg", desc:"For courage, protection, and removal of negative forces.", price:"from $251" },
    { name:"Gaṇapati Homa", dev:"गणपति होम", glyph:"गं", img:"/assets/homas/h1.jpg", desc:"Removes obstacles before any new beginning or venture.", price:"from $201" },
    { name:"Lakṣmī Kubera Homa", dev:"लक्ष्मी कुबेर होम", glyph:"श्रीं", img:"/assets/homas/h4.jpg", desc:"For abundance, wealth, and lasting prosperity.", price:"from $301" },
    { name:"Mṛtyuñjaya Homa", dev:"मृत्युञ्जय होम", glyph:"हौं", img:"/assets/homas/h5.jpg", desc:"For longevity, wellbeing, and freedom from fear.", price:"from $301" },
    { name:"Navagraha Homa", dev:"नवग्रह होम", glyph:"नव", img:"/assets/homas/h6.jpg", desc:"Balances planetary influences for harmony and progress.", price:"from $351" },
    { name:"Śāsta Homa", dev:"शास्ता होम", glyph:"शा", img:"/assets/homas/h7.jpg", desc:"Invokes Lord Ayyappa for peace and family protection.", price:"from $251" },
    { name:"Sudarśana Homa", dev:"सुदर्शन होम", glyph:"हुं", img:"/assets/homas/h8.jpg", desc:"Dispels negativity and shields against unseen harm.", price:"from $301" },
    { name:"Chaṇḍī Saptaśatī Homa", dev:"चण्डी होम", glyph:"ऐं", img:"/assets/homas/h3.jpg", desc:"A grand invocation of the Divine Mother for supreme grace.", price:"from $451" },
  ],

  poojas: [
    { name:"Abhiśeka — Any Deity", dev:"अभिषेक", glyph:"ॐ", img:"/assets/poojas/p1.jpg", desc:"Sacred ceremonial bathing of the chosen deity with offerings.", price:"from $151" },
    { name:"Durgā Pūjā", dev:"दुर्गा पूजा", glyph:"दुं", img:"/assets/poojas/p5.jpg", desc:"Worship of the Divine Mother for strength and protection.", price:"from $151" },
    { name:"Gaṇapati Pūjā", dev:"गणपति पूजा", glyph:"गं", img:"/assets/poojas/p4.jpg", desc:"The auspicious first worship to clear all obstacles.", price:"from $121" },
    { name:"Kalaśa Pūjā", dev:"कलश पूजा", glyph:"कं", img:"/assets/poojas/p2.jpg", desc:"Sanctifies the sacred pot invoking divine presence.", price:"from $121" },
    { name:"Lakṣmī Pūjā", dev:"लक्ष्मी पूजा", glyph:"श्रीं", img:"/assets/poojas/p11.jpg", desc:"Invites prosperity, fortune, and household harmony.", price:"from $151" },
    { name:"Navagraha Pūjā", dev:"नवग्रह पूजा", glyph:"नव", img:"/assets/poojas/p10.jpg", desc:"Honors the nine planets for balance and wellbeing.", price:"from $171" },
    { name:"Rudrābhiśeka", dev:"रुद्राभिषेक", glyph:"नमः", img:"/assets/poojas/p3.jpg", desc:"Powerful abhiṣeka of Lord Śiva for peace and renewal.", price:"from $201" },
    { name:"Sarasvatī Pūjā", dev:"सरस्वती पूजा", glyph:"ऐं", img:"/assets/poojas/p6.jpg", desc:"For knowledge, learning, the arts, and clarity of mind.", price:"from $121" },
    { name:"Śāsta Pūjā", dev:"शास्ता पूजा", glyph:"शा", img:"/assets/poojas/p7.jpg", desc:"Devotional worship of Lord Ayyappa for the family.", price:"from $151" },
    { name:"Satyanārāyaṇa Pūjā", dev:"सत्यनारायण पूजा", glyph:"ॐ", img:"/assets/poojas/p8.jpg", desc:"Worship of Lord Viṣṇu for gratitude and fulfilled vows.", price:"from $151" },
    { name:"Hanumān Pūjā", dev:"हनुमान पूजा", glyph:"राम", img:"/assets/poojas/p9.jpg", desc:"For strength, devotion, and protection from adversity.", price:"from $121" },
  ],

  specialized: [
    { name:"Puruṣa Sūkta Homa", dev:"पुरुष सूक्त होम", glyph:"पुरु", img:"/assets/homas/h1.jpg", desc:"A grand Vedic fire offering using the Puruṣa Sūkta, invoking the cosmic form of the Divine for universal harmony.", price:"from $351" },
    { name:"Medhā Sūktam Homa", dev:"मेधा सूक्तम् होम", glyph:"मेधा", img:"/assets/homas/h2.jpg", desc:"A sacred fire offering with the Medhā Sūktam, invoking blessings of wisdom, memory, and sharp intellect.", price:"from $251" },
    { name:"Bhagavatī Sevā", dev:"भगवती सेवा", glyph:"भग", img:"/assets/poojas/p5.jpg", desc:"Devotional worship offered to the Divine Mother Bhagavatī, invoking her grace, protection, and abundant blessings.", price:"Inquire" },
    { name:"Chaṇḍī Homa", dev:"चण्डी होम", glyph:"ऐं", img:"/assets/homas/h3.jpg", desc:"A powerful homa invoking Goddess Chaṇḍī for strength, protection, and victory over all obstacles.", price:"from $351" },
    { name:"Durgā Pūjā — Bengali", dev:"दुर्गा पूजा (बंगाली)", glyph:"दुं", img:"/assets/poojas/p5.jpg", desc:"The grand Bengali tradition of Durgā worship performed with full ritual procedure, devotion, and festive offerings.", price:"Inquire" },
    { name:"Ekādaśa Vāra Rudra Homa", dev:"एकादश वार रुद्र होम", glyph:"रुद्र", img:"/assets/homas/h8.jpg", desc:"The eleven-fold invocation of Lord Rudra through sacred fire offerings, for peace, health, and liberation from suffering.", price:"from $501" },
    { name:"Ekādaśa Vāra Rudra Pūjā / Abhiśeka", dev:"एकादश वार रुद्र पूजा", glyph:"रुद्र", img:"/assets/poojas/p3.jpg", desc:"Eleven sacred repetitions of Rudra worship and ceremonial abhiṣeka, invoking Lord Śiva's grace for healing and renewal.", price:"from $351" },
    { name:"Graha Praveśa / Vāstu Śānti", dev:"गृह प्रवेश / वास्तु शान्ति", glyph:"गृह", img:"/assets/poojas/p2.jpg", desc:"The sacred housewarming ceremony and Vāstu Śānti ritual to bless, purify, and consecrate a new home or space.", price:"Inquire" },
    { name:"Guru Śānti Homa", dev:"गुरु शान्ति होम", glyph:"गुरु", img:"/assets/homas/h7.jpg", desc:"A sacred fire ritual honoring the Guru lineage and seeking blessings of wisdom, guidance, and spiritual peace.", price:"from $251" },
    { name:"Mahārudram", dev:"महारुद्रम्", glyph:"रुद्र", img:"/assets/homas/h5.jpg", desc:"The magnificent Mahārudram — an extended, powerful invocation of Lord Śiva with full Vedic recitation and ritual offerings.", price:"Inquire" },
    { name:"Manda Maṅgala Śānti Homa", dev:"मन्द मङ्गल शान्ति होम", glyph:"शान्ति", img:"/assets/homas/h6.jpg", desc:"A peace-restoring homa addressing the combined planetary influence of Saturn and Mars, performed for harmony and protection.", price:"from $301" },
    { name:"Nakṣatra Homa", dev:"नक्षत्र होम", glyph:"नक्ष", img:"/assets/homas/h6.jpg", desc:"A fire ritual dedicated to your birth star, invoking its presiding deity for harmony, health, and auspiciousness in life.", price:"from $251" },
    { name:"Parihāra for Jyotiṣa Services", dev:"परिहार ज्योतिष सेवा", glyph:"ग्रह", img:"/assets/poojas/p1.jpg", desc:"Personalized Vedic astrological remedies — tailored rituals, offerings, and prayers to address specific planetary imbalances.", price:"Inquire" },
    { name:"Pitṛdoṣa Nivāraṇa Homa", dev:"पितृदोष निवारण होम", glyph:"पितृ", img:"/assets/homas/h5.jpg", desc:"A sacred fire ritual performed to alleviate ancestral afflictions, bringing peace to departed souls and harmony to the family.", price:"from $351" },
    { name:"Sahasra Liṅgārchana", dev:"सहस्र लिङ्गार्चन", glyph:"नमः", img:"/assets/poojas/p3.jpg", desc:"The sacred offering of one thousand bilva leaves or flowers to the Śiva Liṅga, performed for deep devotion and divine grace.", price:"Inquire" },
    { name:"Sahasranāma Archana", dev:"सहस्रनाम अर्चना", glyph:"ॐ", img:"/assets/poojas/p1.jpg", desc:"The recitation of one thousand divine names of a deity, accompanied by flower offerings, for blessings and liberation.", price:"from $151" },
    { name:"Śani Śānti Homa", dev:"शनि शान्ति होम", glyph:"शनि", img:"/assets/homas/h6.jpg", desc:"A fire ritual dedicated to Lord Śani to pacify Saturn's influence and restore balance, peace, and forward progress in life.", price:"from $251" },
    { name:"Sarasvatī Pūjā — Bengali", dev:"सरस्वती पूजा (बंगाली)", glyph:"ऐं", img:"/assets/poojas/p6.jpg", desc:"The celebrated Bengali tradition of Sarasvatī worship, performed with devotion, offerings, and the spirit of festive learning.", price:"Inquire" },
    { name:"Svayamvarā Kalā Pārvatī Homa", dev:"स्वयम्वर काला पार्वती होम", glyph:"श्रीं", img:"/assets/homas/h3.jpg", desc:"A sacred homa invoking Goddess Svayamvarā Pārvatī for blessings of a harmonious marriage, love, and companionship.", price:"from $301" },
    { name:"Manyu Sūktam Homa", dev:"मन्यु सूक्तम् होम", glyph:"मन्यु", img:"/assets/homas/h5.jpg", desc:"A powerful fire offering using the Manyu Sūktam, invoking divine strength, courage, and protection from adversity.", price:"from $251" },
  ],

  samskaras: [
    { name:"Akṣarābhyāsa", dev:"अक्षराभ्यास", glyph:"अ", desc:"A child's sacred initiation into the world of learning.", price:"Inquire" },
    { name:"Anna Śrāddha with Homa", dev:"अन्न श्राद्ध", glyph:"पितृ", desc:"Reverent rites honoring departed ancestors.", price:"Inquire" },
    { name:"Annaprāśana / Chorūṇu", dev:"अन्नप्राशन", glyph:"अन्न", desc:"The joyful first-feeding ceremony for an infant.", price:"Inquire" },
    { name:"Āyushya Homa", dev:"आयुष्य होम", glyph:"आयु", desc:"Blessings of long life and vitality, often on birthdays.", price:"Inquire" },
    { name:"Bhīmaratha Śānti", dev:"भीमरथ शान्ति", glyph:"७०", desc:"A revered ceremony marking the 70th birthday.", price:"Inquire" },
    { name:"Garbhādāna", dev:"गर्भादान", glyph:"गर्भ", desc:"The sacred rite welcoming the journey of parenthood.", price:"Inquire" },
    { name:"Hiraṇya Śrāddha", dev:"हिरण्य श्राद्ध", glyph:"पितृ", desc:"An ancestral offering performed with devotion.", price:"Inquire" },
    { name:"Jātakarma", dev:"जातकर्म", glyph:"जन्म", desc:"The birth ceremony welcoming a newborn into dharma.", price:"Inquire" },
    { name:"Kalyāṇa — Wedding", dev:"कल्याण", glyph:"विवाह", desc:"The sacred Vedic union of two souls in marriage.", price:"Inquire" },
    { name:"Kanakābhiṣeka", dev:"कनकाभिषेक", glyph:"१००", desc:"A grand celebration honoring the 100th birthday.", price:"Inquire" },
  ],

  classes: [
    { name:"Bhagavad Gītā", dev:"भगवद्गीता", glyph:"गी", desc:"Verse-by-verse study of Krishna's timeless teaching.", level:"All levels", cadence:"Weekly" },
    { name:"Viṣṇu Sahasranāma", dev:"विष्णु सहस्रनाम", glyph:"ॐ", desc:"Learn the meaning and chanting of the thousand names.", level:"Intermediate", cadence:"Weekly" },
    { name:"Sanskrit Basics", dev:"संस्कृत", glyph:"सं", desc:"Read, write, and pronounce the language of the Vedas.", level:"Beginner", cadence:"Bi-weekly" },
    { name:"Stotras & Chanting", dev:"स्तोत्र", glyph:"श्लो", desc:"Master devotional hymns with correct intonation.", level:"All levels", cadence:"Weekly" },
    { name:"Hindu Philosophy", dev:"दर्शन", glyph:"दर्", desc:"Explore Vedānta and the six darśanas of thought.", level:"Advanced", cadence:"Monthly" },
    { name:"Children's Dharma", dev:"बाल धर्म", glyph:"बाल", desc:"Stories, values, and traditions for young hearts.", level:"Ages 5–12", cadence:"Weekly" },
    { name:"Yoga & Meditation", dev:"योग", glyph:"ध्यान", desc:"Āsana, prāṇāyāma, and stillness for body and mind.", level:"All levels", cadence:"Twice weekly" },
    { name:"Cultural Learning", dev:"संस्कृति", glyph:"कला", desc:"Festivals, music, and the living arts of our heritage.", level:"All levels", cadence:"Monthly" },
  ],

  grow: [
    { name:"Spiritual Counseling", dev:"मार्गदर्शन", glyph:"ॐ", desc:"Compassionate, confidential guidance rooted in dharma." },
    { name:"Astrology Guidance", dev:"ज्योतिष", glyph:"ग्रह", desc:"Vedic jyotiṣa readings for clarity on life's path." },
    { name:"Meditation Support", dev:"ध्यान", glyph:"ध्या", desc:"Personalized practice to cultivate inner stillness." },
    { name:"Family Dharma Guidance", dev:"कुल धर्म", glyph:"कुल", desc:"Helping families honor traditions across generations." },
    { name:"Youth & Children's Learning", dev:"बाल शिक्षा", glyph:"बाल", desc:"Nurturing the next generation with values and joy." },
    { name:"Community Events", dev:"उत्सव", glyph:"उत्", desc:"Festivals, satsangs, and gatherings that bring us together." },
  ],

  tiers: [
    { name:"Śraddhā", dev:"श्रद्धा", price:"$9", per:"/mo", featured:false,
      benefits:["Access to recorded class library","Monthly newsletter & event updates","Member-only resource downloads"] },
    { name:"Dharma", dev:"धर्म", price:"$19", per:"/mo", featured:true,
      benefits:["Everything in Śraddhā","Live weekly scripture classes","Discounted service bookings","Priority event registration"] },
    { name:"Sevā", dev:"सेवा", price:"$39", per:"/mo", featured:false,
      benefits:["Everything in Dharma","One quarterly guided pooja","Personal spiritual check-ins","Family learning track access"] },
    { name:"Vṛkṣa Patron", dev:"वृक्ष", price:"$99", per:"/mo", featured:false,
      benefits:["Everything in Sevā","Founding-supporter recognition","Annual private ceremony","Direct line to our ācāryas"] },
  ],

  steps: [
    { glyph:"१", t:"Choose a Service", d:"Browse poojas, homas, samskaras, and classes." },
    { glyph:"२", t:"Online or In-Person", d:"Join virtually or invite us to your home or venue." },
    { glyph:"३", t:"Pick Date & Time", d:"Select a muhūrta that suits your family." },
    { glyph:"४", t:"Submit Details", d:"Share saṅkalpa details and any special intentions." },
    { glyph:"५", t:"Receive Confirmation", d:"Get instant confirmation and a preparation guide." },
  ],
};
